In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("../data/GSE10245_expression.csv")

In [30]:
df

,ID_REF,GSM258551,GSM258552,GSM258553,GSM258554,GSM258555,GSM258556,GSM258557,GSM258558,GSM258559,...,GSM258599,GSM258600,GSM258601,GSM258602,GSM258603,GSM258604,GSM258605,GSM258606,GSM258607,GSM258608
0,1007_s_at,9.129905,9.843349,9.730661,9.032165,10.281793,9.154551,8.063788,8.881805,9.039005,...,9.628212,10.130757,9.276419,9.296957,10.346701,9.709068,7.672985,9.199080,7.635765,8.760082
1,1053_at,8.034022,7.973332,8.834045,7.723965,9.040800,8.792375,8.093354,7.575620,8.438594,...,9.215567,8.273698,8.790710,8.861625,8.512193,7.908581,9.299454,8.220959,7.432135,7.596431
2,117_at,3.564520,4.994852,5.066018,4.958580,4.951835,6.428274,7.364676,4.659326,6.643723,...,5.183919,4.801579,6.161777,5.443126,4.609810,4.339004,6.384404,6.006534,5.484470,5.372583
3,121_at,4.746490,5.197306,5.234618,6.078180,5.205632,5.009848,5.533000,5.362637,5.210988,...,5.202508,4.807654,5.326347,5.205004,5.201123,6.028717,5.220915,5.186452,5.220778,5.097535
4,1255_g_at,2.320698,2.248520,2.259504,2.262787,2.207531,2.322618,2.656929,2.255955,2.266399,...,2.248392,2.232021,2.246738,2.245739,2.265454,2.301397,2.322604,2.236494,2.243698,2.420731
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54670,AFFX-r2-Ec-bioC-5_at,10.730983,9.719266,9.101115,9.763076,9.651785,9.716659,10.224866,9.968033,9.698518,...,9.163981,10.212906,9.111832,9.888466,9.901881,9.814137,9.586620,9.593082,10.066312,10.343148
54671,AFFX-r2-Ec-bioD-3_at,13.599488,12.847711,12.384142,12.969199,12.924465,12.996885,13.180944,13.074864,12.782987,...,12.621897,13.323579,12.505348,13.021481,13.137414,13.131295,12.736871,12.864534,13.248409,13.357006
54672,AFFX-r2-Ec-bioD-5_at,13.031726,12.250033,11.798363,12.307684,12.243207,12.369919,12.688711,12.541047,12.103870,...,12.027085,12.834769,11.794169,12.425024,12.580205,12.448659,12.081561,12.227276,12.616884,12.776164
54673,AFFX-r2-P1-cre-3_at,15.028729,14.440756,14.439887,14.557363,14.612223,14.593751,14.697993,14.626500,14.546733,...,14.432716,14.779129,14.291955,14.539678,14.888295,14.719894,14.534358,14.413188,14.705226,14.719894
54674,AFFX-r2-P1-cre-5_at,14.586347,14.072366,14.011392,14.162145,14.122751,14.202961,14.339175,14.292254,14.058803,...,14.062622,14.471579,13.927947,14.149317,14.425394,14.362869,14.046082,14.083899,14.369607,14.371899

In [31]:
df.shape

(54675, 59)

In [32]:
df_meta = pd.read_csv("../data/GSE10245_metadata.csv")

In [33]:
df_meta.head()

,sample,title,geo_accession,status,submission_date,last_update_date,type,channel_count,source_name_ch1,organism_ch1,...,contact_institute,contact_address,contact_city,contact_zip/postal_code,contact_country,supplementary_file,relation,series_id,data_row_count,char0+disease state
0,GSM258551,NSCLC_AC_10,GSM258551,Public on Oct 01 2009,Jan 23 2008,Aug 28 2018,RNA,1,human non-small cell lung cancer tumor tissue,Homo sapiens,...,German Cancer Research Center and National Cen...,Im Neuenheimer Feld 460,Heidelberg,69120,Germany,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM258n...,Reanalyzed by: GSE60486,GSE10245,54675,adenocarcinoma
1,GSM258552,NSCLC_AC_16,GSM258552,Public on Oct 01 2009,Jan 23 2008,Aug 28 2018,RNA,1,human non-small cell lung cancer tumor tissue,Homo sapiens,...,German Cancer Research Center and National Cen...,Im Neuenheimer Feld 460,Heidelberg,69120,Germany,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM258n...,Reanalyzed by: GSE60486,GSE10245,54675,adenocarcinoma
2,GSM258553,NSCLC_SCC_22,GSM258553,Public on Oct 01 2009,Jan 23 2008,Aug 28 2018,RNA,1,human non-small cell lung cancer tumor tissue,Homo sapiens,...,German Cancer Research Center and National Cen...,Im Neuenheimer Feld 460,Heidelberg,69120,Germany,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM258n...,Reanalyzed by: GSE60486,GSE10245,54675,squamous cell carcinoma
3,GSM258554,NSCLC_AC_24,GSM258554,Public on Oct 01 2009,Jan 23 2008,Aug 28 2018,RNA,1,human non-small cell lung cancer tumor tissue,Homo sapiens,...,German Cancer Research Center and National Cen...,Im Neuenheimer Feld 460,Heidelberg,69120,Germany,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM258n...,Reanalyzed by: GSE60486,GSE10245,54675,adenocarcinoma
4,GSM258555,NSCLC_SCC_25,GSM258555,Public on Oct 01 2009,Jan 23 2008,Aug 28 2018,RNA,1,human non-small cell lung cancer tumor tissue,Homo sapiens,...,German Cancer Research Center and National Cen...,Im Neuenheimer Feld 460,Heidelberg,69120,Germany,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM258n...,Reanalyzed by: GSE60486,GSE10245,54675,squamous cell carcinoma

In [34]:
#Import preprocessing functions and build dataset

In [35]:
from src.preprocess import build_dataset

In [36]:
X, y = build_dataset("../data/GSE10245_expression.csv", "../data/GSE10245_metadata.csv")

In [37]:
print(X.shape)
X.head()

(58, 2000)

ID_REF,201820_at,209125_at,206291_at,211735_x_at,205982_x_at,202831_at,38691_s_at,205064_at,224588_at,220542_s_at,...,229414_at,210721_s_at,230104_s_at,243154_at,227874_at,234350_at,244387_at,237054_at,206104_at,211417_x_at
GSM258551,-0.745196,-0.929726,-0.604171,1.239897,1.246148,0.270563,1.137520,-0.745675,-0.626525,0.781607,...,1.520054,-0.258120,-0.163492,-0.703929,1.530263,0.882377,-0.782111,-0.767050,-0.413872,0.202198
GSM258552,-0.695632,1.072825,-0.637732,0.967739,0.940318,-1.114206,0.987023,-0.752172,1.797316,0.928772,...,0.370819,-0.493882,-0.470469,0.455698,0.216005,1.858352,0.674153,-0.366614,-0.434249,-0.600002
GSM258553,-0.332156,1.624416,1.527851,0.797054,0.809303,1.049296,0.844122,1.654143,-0.633631,0.285160,...,-1.042836,3.713918,1.282709,-0.923362,-0.190225,-0.143587,-0.992810,-0.011669,-0.409349,-1.088697
GSM258554,-0.618058,-0.506619,-0.627259,0.533615,0.489568,0.761164,0.594191,-0.741347,-0.629516,0.036625,...,-0.497970,-0.326945,-0.018483,-0.045336,0.051345,1.011724,0.280012,0.524839,-0.405246,-0.448941
GSM258555,1.642785,1.505289,1.803120,-1.088557,-1.207323,1.366294,-1.318392,1.285315,-0.649219,-0.883310,...,-0.987881,2.236740,1.317389,0.710814,-0.568791,-2.385781,-0.438419,-1.552696,-0.417197,0.442288

In [38]:
print(y.value_counts())
print(y.value_counts(normalize=True))

char0+disease state
1    40
0    18
Name: count, dtype: int64
char0+disease state
1    0.689655
0    0.310345
Name: proportion, dtype: float64

In [40]:
 X.to_csv("../data/X_processed.csv")
 y.to_csv("../data/y_labels.csv")